// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uffldsqlwwgqzegyybfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZmxkc3Fsd3dncXplZ3l5YmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDYwNjEsImV4cCI6MjA2NzgyMjA2MX0.NtQ5BexY5vYgeUZg7IbtTW_I94FCsHjgO62Gtdwv9GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});